name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Determine bump type
        id: bump
        run: |
          # Récupérer le nombre de fichiers modifiés dans la PR
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | wc -l)
          
          # Déterminer le type de bump en fonction du nombre de fichiers modifiés
          if [ "$FILES_CHANGED" -gt 20 ]; then
            echo "Bump major"
            echo "type=major" >> $GITHUB_OUTPUT
          elif [ "$FILES_CHANGED" -gt 5 ]; then
            echo "Bump minor"
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "Bump patch"
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        run: npm run version:${{ steps.bump.outputs.type }}

      - name: Build
        run: npm run release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: sync.exe
          generate_release_notes: true
          tag_name: v$(node -p "require('./package.json').version")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}